language: java
jdk:
- oraclejdk8
install: true
dist: trusty
os: linux
git:
  depth: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- gpg --import travis/all.gpg
- cp travis/settings.xml $HOME/.m2/settings.xml
jobs:
  include:
  - stage: build
    script: mvn --batch-mode -U clean install
  - stage: startRelease
    script: mvn --batch-mode -U clean jgitflow:release-start -PgitflowStart
  - stage: finishRelease
    script: mvn --batch-mode -U clean jgitflow:release-finish
stages:
- name: build
  if: branch !~ ^release.*$
- name: startRelease
  if: (branch = "develop") AND (env(RELEASE) IS present AND env(RELEASE) = true)
- name: finishRelease
  if: branch =~ ^release.*$
